# /.socket doesn't copy-up, it's direct write. Put rbenv
# on a copy-up layer in FST to allow write-access by admin
# Downside is that anything root installs will also propagate
# to child nodes, so don't do that!
---
- set_fact:
    __rbenv_version: "v{{ rbenv_version }}"
- name: Prepare {{ git_target }}
  file:
    path: "{{ git_target|dirname}}"
    state: directory
- name: Install rbenv
  include_role: name="{{ role_path }}/../rbenv-support"
  vars:
    rbenv_root: "{{ apnscp_filesystem_template }}/{{rbenv_service_install }}/{{ git_target }}"
    rbenv_tmpdir: "{{ apnscp_root }}/storage/cache"
    rbenv:
      env: system
      default_ruby:   
      version: "{{ __rbenv_version }}"
      rubies: []
  register: rc
- name: Link {{ git_target }}
  file:
    path: "{{ git_target }}"
    src: "{{ apnscp_filesystem_template }}/{{rbenv_service_install }}/{{git_target}}"
    state: link
- name: Get rbenv code
  command: "{{ git_target }}/bin/rbenv init -"
  register: rbenv_code
- name: Create rbenv.sh
  copy:
    dest: "{{ rbenv_script }}"
    content: |
      #!/bin/sh
      {{ rbenv_code.stdout }}
    mode: 0644
  register: rbenv_create
- name: Link rbenv to /usr/bin
  file:
    path: "/usr/bin/rbenv"
    src: "{{ git_target }}/bin/rbenv"
    state: link
- name: Check if {{ sys_ruby_version }} installed
  stat: path={{ git_target }}/versions/{{sys_ruby_version | default("")}}
  register: rv
# Install Ruby manually to avoid using incorrect FST markup in playbook
- name: Build Ruby {{ sys_ruby_version }} outside FST
  shell: >
    $SHELL -lc "{{ git_target }}/bin/rbenv install {{ sys_ruby_version }}"
  environment: 
    TMPDIR: "{{ apnscp_root }}/storage/cache"
    RBENV_SHELL: bash
    RBENV_ROOT: "{{ git_target }}"
  when: sys_ruby_version is defined and not rv.stat.exists
- name: Add {{ git_target }} to wheel
  command: >
    find {{ git_target | quote }} -follow  
      -iname ".git" -prune -o -not -group wheel -print 
      -exec chgrp wheel {} +
  register: rbenv_chown
  changed_when: rbenv_chown.stdout != ""
- name: Ensure wheel has permissions to install binaries
  file:
    path: "{{ apnscp_filesystem_template }}/{{rbenv_service_install }}/{{git_target}}/{{ item }}"
    mode: g+rwx
    state: directory
    group: wheel
    owner: root
  with_items:
    - versions
    - shims
# Stolen from rbenv-support playbook, needs late init to correct path
- name: Check if current system ruby version is {{ sys_ruby_version }}
  shell: $SHELL -lc "{{ git_target }}/bin/rbenv version | cut -d ' ' -f 1 | grep -Fx '{{ sys_ruby_version }}'"
  register: ruby_selected
  changed_when: false
  ignore_errors: yes
  failed_when: false
  check_mode: no

- name: Set Ruby {{ sys_ruby_version }} for system
  become: yes
  shell: $SHELL -lc "{{ git_target }}/bin/rbenv global {{ sys_ruby_version }} && {{ git_target }}/bin/rbenv rehash"
  when:
    - ruby_selected.rc != 0

# Back to apnscp
- name: Check for rbenv.sh in FST
  stat: path="{{ apnscp_filesystem_template }}/{{ rbenv_service_install }}/{{rbenv_script}}"
  register: s
- name: Link rbenv.sh to FST
  include_tasks: roles/common/tasks/copy-link.yml
  vars: 
    src: "{{ rbenv_script }}"
    path: "{{ apnscp_filesystem_template }}/{{ pyenv_service_install }}/{{rbenv_script}}"
    notify: Reload filesystem template
  when: rbenv_create.changed or not s.stat.exists
