---
php_pecl_install_command: "pecl install"
# Add extensions to this list to have them installed with this role.
php_pecl_extensions: []
phpconfig: /usr/bin/php-config
phpize: /usr/bin/phpize
extra_flags: ""
bypass_pecl_ini: 0