---
- include_vars: vars/ftp.yml
- lineinfile: 
    path: "{{ pam_file }}"
    regexp: '^[^#]*auth.*{{vwh_module}}'
    line: "auth\trequired\t{{ vwh_module }}"
    insertbefore: '^[^#]*auth.*password-auth'
    state: present  
- include_tasks: listfile.yml
  vars: 
    file: "/etc/ftp.pamlist"  
- include_tasks: cgroup.yml