---
- include_tasks: ./sshd.yml
- include_tasks: ./su.yml
- include_tasks: ./ftp.yml
- include_tasks: crond.yml
- name: Configure Dovecot services
  include_tasks: ./dovecot.yml
  vars:
    pam_service: "{{ dovecot_service }}"
    pam_file: "{{ pam_path }}/{{ dovecot_service }}"
  with_items: "{{ dovecot_services }}"
  loop_control:
    loop_var: dovecot_service
    label: "Configuring Dovecot service {{ dovecot_service }}"
- name: "Edit {{ apnscp_filesystem_template }} system-auth"
  lineinfile:
    path: "{{ apnscp_filesystem_template }}/siteinfo/etc/pam.d/system-auth"
    regexp: '^\s*session\s+.*pam_cgroup\.so'
    line: "session\toptional\tpam_cgroup.so"
    insertbefore: '^\s*session\s*required\s*{{ vwh_module }}|$'
    state: present
- name: "Require login shell to be listed in /etc/shells"
  lineinfile:
    path: "/etc/pam.d/system-auth"
    regexp: 'auth\s+.*pam_shells\.so'
    line: "auth\trequired\tpam_shells.so"
    state: present
    insertbefore: "account\\s"
