---
- copy:
    src: ./templates/su
    dest: "{{ apnscp_filesystem_template }}/siteinfo/etc/pam.d/su"
    force: no
- include_tasks: cgroup.yml
  vars:
    pam_file: "{{ apnscp_filesystem_template }}/siteinfo/etc/pam.d/su"