# Copyright (c) 2017 Apis Networks
# vim:ft=ansible:
---
- name: "Save PostgreSQL password"
  lineinfile: 
    path: "{{ passwdfile }}"
    regexp: '^([^:]+:){3}root:'
    create: yes
    line: localhost:*:*:root:{{password}}
    mode: 0600