- name: noop    
  debug: msg="noop handler" verbosity=4
- name: start mariadb
  systemd: name=mariadb state=started enabled=yes
  listen: start mariadb
- name: initialize pgsql
  include_tasks: "{{ role_path }}/handlers/initialize-pgsql.yml"
  listen: install pgsql
- name: enable postgresql
  systemd:
    daemon_reload: yes
    enabled: yes
    state: started
    name: postgresql-{{pgversion}}
  listen: install pgsql
