---
- hosts: localhost  
  tasks:
    - include_role: name=common/fail-and-save
      vars:
        msg: |
            Ansible 2.5.1 is installed and has been downgraded automatically to
            2.4.2. A restart is necessary.

            See ansible/ansible#38271 for details of downgrade.
      when: true