---
- hosts: localhost  
  vars:
    apnscp_user_defaults: /root/apnscp-ansible-defaults.yml
  vars_files:
    - './apnscp-vars.yml'
    - 'roles/common/vars/apnscp-internals.yml'
    - ['{{ apnscp_user_defaults }}', '/dev/null']
  roles:
    - mail/configure-courier-authlib