---
- hosts: localhost
  gather_facts: no
  vars_files:
    - 'apnscp-vars.yml'
    - 'roles/common/vars/apnscp-internals.yml'
    - ['{{ apnscp_user_defaults }}', '/dev/null']
    - ['{{ apnscp_last_run_vars }}', '/dev/null']
  #vars:
  vars:
    apnscp_user_defaults: /root/apnscp-vars.yml
    test:
      siteinfo:
        - package: sudo
        - package: acl
        - package: alsa-lib
        - package: apr-util
          when: true
        - package: apr
          when: false
  roles:
    - apnscp/initialize-filesystem-template
  tasks:
    - fail:
        msg: >
          {{ lookup('items', test['siteinfo']) |
            rejectattr('when', 'defined') | list | join(' ') }}
