---
- hosts: localhost
  vars:
    apnscp_user_defaults: /root/apnscp-vars.yml
  vars_files:
    - 'apnscp-vars.yml'
    - 'roles/common/vars/apnscp-internals.yml'
    - ['{{ apnscp_user_defaults }}', '/dev/null']
    - ['{{ apnscp_last_run_vars }}', '/dev/null']
  tasks:
    - include_tasks: "{{ playbook_dir }}/roles/apnscp/bootstrap/tasks/set-config.yml" 
      vars: 
        section: rampart 
        option: "{{ item.option }}"
        value: "{{ item.value }}"
      with_items:
        - {option: driver, value: "ipset" }
        - {option: prefix, value: "fail2ban-" }

