---
- hosts: localhost  
  tasks:
    - set_fact:
        str: "foo"
    - name: Append
      set_fact:
        str: "{{ str + item }}"
      with_items: 
        - bar
        - baz
    - debug: msg="{{ str }}"