---
- hosts: localhost
  vars:
    apnscp_user_defaults: /root/apnscp-vars.yml
  vars_files:
    - 'apnscp-vars.yml'
    - 'roles/common/vars/apnscp-internals.yml'
    - ['{{ apnscp_user_defaults }}', '/dev/null']
    - ['{{ apnscp_last_run_vars }}', '/dev/null']
  tasks:
    - name: Move whitelist to trusted
      firewalld:
        zone: trusted
        permanent: true
        source: "ipset:whitelist"
        state: disabled
