---
- hosts: localhost
  gather_facts: no
  vars_files:
    - 'apnscp-vars.yml'
    - 'roles/common/vars/apnscp-internals.yml'
    - ['{{ apnscp_user_defaults }}', '/dev/null']
    - ['{{ apnscp_last_run_vars }}', '/dev/null']
  #vars:
  vars:
    apnscp_user_defaults: /root/apnscp-vars.yml
    test:
      siteinfo:
        - package: sudo
        - package: acl
        - package: alsa-lib
        - package: apr-util
          when: true
        - package: apr
          when: false
  tasks:
    - name: Check for rspamd existence
      systemd: name=rspamd state=restarted
      register: r
      failed_when: >
        "msg" in r and r.msg.find("Could not find the") == -1 or
        "status" in r and (r.status.ExecMainCode | int) != 0
    - fail: msg="{{ r }}"
