---
- hosts: localhost
  gather_facts: no
  vars_files:
    - 'apnscp-vars.yml'
    - 'roles/common/vars/apnscp-internals.yml'
    - ['{{ apnscp_user_defaults }}', '/dev/null']
    - ['{{ apnscp_last_run_vars }}', '/dev/null']
  vars:
    test:
      siteinfo:
        - package: sudo
        - package: acl
        - package: alsa-lib
        - package: apr-util
          when: true
        - package: apr
          when: false
  tasks:
    - name: Override check
      include_role: name=systemd/override-config
      vars:
        service: watchdog-pinga
        config:
          - group: Service
            vars:
              LimitNOFILE: 4096
              TimeoutStartSec: "{{ fail2ban_service_timeout }}"
              TimeoutStopSec: "{{ fail2ban_service_timeout }}"
