---
- hosts: localhost
  become: yes
  connection: local
  gather_facts: yes
  vars_files:
    - 'apnscp-vars.yml'
    - 'roles/common/vars/apnscp-internals.yml'
  roles:      
    #- system/selinux
    - fail2ban/configure-jails