---
- include_tasks: verify-and-install.yml
  vars:
    extension: "{{ itr_extension }}"
  with_items: "{{ pecl_extensions }}"
  loop_control:
    loop_var: itr_extension
  when: pecl_extensions is defined
