# Force PECL install with --extra-vars 'force_install'
---
- include_role:
    name: php/common
    tasks_from: query-extension-dir  
- name: Register ini directory
  block:
    - command: "{{ phpconfig }} --php-binary"
      register: bin
    - command: "{{ bin.stdout }} -r 'print PHP_CONFIG_FILE_SCAN_DIR; exit(defined(\"PHP_CONFIG_FILE_SCAN_DIR\") ? 0 : 1);'"
      register: scandir
    - set_fact: scandir="{{scandir.stdout}}"
- name: Update channel protocols
  command: pecl channel-update pecl.php.net
  run_once: true
- name: Verify if PECL extension installed.
  vars: 
    modname: "{{ extension | basename | regex_replace('^([^-.]+).*$', '\\1') }}"
  block: 
    - name: "Verify {{ modname }} module installed"
      stat: path="{{ php_module_directory }}/{{ modname }}.so"
      register: stres
    - name: "Build and install {{ modname }} library."
      command: "{{ role_path }}/files/installPecl.sh {{ extension }}"
      environment:
        PHPIZE: "{{ phpize }}"
        PHPCONFIG: "{{ phpconfig }}"
        XTRACFG: "{{ extra_flags }}"
        MAKEFLAGS: "-j{{ ansible_processor_vcpus }}"    
      notify: Restart apache
      when: not stres.stat.exists or force is defined and force
      register: module_install
    - name: "Verify {{ scandir }}/{{modname}}.ini exists"
      stat:
        path: "{{ scandir }}/{{ modname }}.ini"
      register: st
    - name: Add PECL module configuration
      copy: 
        dest: "{{ scandir }}/{{modname}}.ini"
        content: "extension={{modname}}.so\n"
      when: > 
        module_install.changed and 
        not st.stat.exists and
        bypass_pecl_ini is not defined
