---
nscd_replacements: 
  - {field: passwd, state: "no"}
  - {field: group, state: "yes"}
  - {field: hosts, state: "yes"}
  - {field: netgroup, state: "{{ enable_netgroup_caching | default(false) | bool | ternary('yes', 'no') }}"}