---
- name: Enable apnscp testing
  ini_file:
    path: /etc/yum.repos.d/apnscp-testing.repo
    section: apnscp-testing
  with_items:
    - { option: enabled, value: "{{ apnscp_testing_repo | int }}" }
    - { option: priority, value: 2 }