---
title: Fedora Extra Packages Library
bootstrap:    
  - repo_rpm: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm"
    repo_key: "/etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}"
repo_name: epel
rpms:
  - clamav
  - clamav-data
  - clamav-devel
  - clamav-filesystem
  - clamav-lib
  - clamav-scanner
  - clamav-scanner-systemd
  - clamav-server
  - clamav-server-systemd
  - clamav-unofficial-sigs
  - clamav-update
  - compat-libtidy
  - compat-libtidy-devel
  - etckeeper
  - fail2ban
  - fail2ban-firewalld
  - fail2ban-sendmail
  - fail2ban-server
  - fail2ban-systemd
  - fcgi
  - fcgi-devel
  - gyp
  - hdf5
  - iperf
  - jemalloc
  - libbsd
  - libc-client
  - libdap
  - libdb4
  - libdb4-devel
  - libgta
  - libjoedog
  - liblzf
  - libmcrypt
  - libmcrypt-devel
  - libnghttp2
  - libnghttp2-devel
  - libopendkim
  - libsodium
  - libsodium-devel
  - libstemmer
  - libuv
  - libuv-devel
  - lz4
  - ncftp
  - netcdf
  - nghttp2
  - nss-mdns
  - ogdi
  - opendbx
  - opendkim
  - openjpeg2
  - openvpn
  - perl-Convert-BinHex
  - perl-Curses
  - perl-Data-Buffer
  - perl-Digest-MD2
  - perl-ExtUtils-XSBuilder
  - perl-generators
  - perl-Geo-IP
  - perl-Getopt-Simple
  - perl-IO-Socket-Timeout
  - perl-Mail-Sender
  - perl-MIME-tools
  - perl-MIME-Types
  - perl-Net-IP
  - perl-PerlIO-via-Timeout
  - perl-Razor-Agent
  - perl-Redis
  - perl-Unix-Syslog
  - pkcs11-helper
  - proj
  - python2-pip
  - python-redis
  - pyzor
  - re2c
  - redis
  - scons
  - Xaw3d
  - yaml-cpp
