---
mail_configure_postfix_marker: true
aliases_file: /etc/aliases
postfix_conf_dir: /etc/postfix
# apnscp-specific lookup file for database configuration
postfix_control_file: "{{ postfix_conf_dir }}/mailboxes.cf"
# Allow unauthenticated relaying from 127.0.0.1
# See also StealCat malware
postfix_relay_mynetworks: false

postfix_sysuser: postfix
postfix_sysgroup: postfix
postfix_user: postfix
# Override to force a password otherwise randomly assigned
postfix_password:
# Don't touch.
postfix_db: "{{ appliance_db }}"
template_files:
  - mailboxes.cf.j2
  - uids.cf.j2
  - virtual_filter.cf.j2
  - aliases.cf.j2
  - postscreen_access.cidr.j2
  - client_access.j2
  - domains.cf.j2

postfix_inet_interfaces: "{{ mail_enabled | bool | ternary('all','loopback-only') }}"
postfix_mydomain: "{{ data_center_mode | bool | ternary(ansible_nodename, None) }}"
# PostSRS
postsrs_sender_map_port: 10001
postsrs_recipient_map_port: 10002
