---
######################################
# Custom Postfix configuration format:
# postfix_custom_config:
#   vmaildrop_destination_rate_delay: 30
#   maximal_backoff_time: 16h
######################################

mail_configure_postfix_marker: true
postfix_conf_dir: /etc/postfix
######################################
# Custom Postfix configuration format:
# postfix_custom_config:
#   vmaildrop_destination_rate_delay: 30
#   maximal_backoff_time: 16h
######################################
# Configure in data_center_mode to enable a centralized memcache server
# Server formatted as ip.addr:port, [ip6::addr]:port, or /path/to/unix/domain.sock
postfix_memcache_server:
#
# Smarthost support- relay all outbound mail through
# this nexthop. May be GMail, Mailchannels, etc
#
# host MUST be set and typically follows the form '[some.host.name]'
# omitting "[]" implies an MX check will be done to determine the
# appropriate hostname
#
# This is applied unconditionally to all mail leaving. Use a transport map
# for per-domain filtering
#
postfix_smarthost_enabled: false
postfix_smarthost_credentials:
  host:
  username:
  password:
postfix_smarthost_auth_file: "{{ postfix_conf_dir }}/smarthost-auth"

aliases_file: /etc/aliases
postfix_data_dir: /var/lib/postfix
# apnscp-specific lookup file for database configuration
postfix_control_file: "{{ postfix_conf_dir }}/mailboxes.cf"
# Allow unauthenticated relaying from 127.0.0.1
# See also StealCat malware
postfix_relay_mynetworks: false
# Add SASL login name to Received: header.
# Note this is shared with the entire world.
postfix_add_sasl_auth_header: false

postfix_sysuser: postfix
postfix_sysgroup: postfix
postfix_user: postfix
# Override to force a password otherwise randomly assigned
postfix_password:
# Don't touch.
postfix_db: "{{ appliance_db }}"
template_files:
  - mailboxes.cf.j2
  - uids.cf.j2
  - virtual_filter.cf.j2
  - aliases.cf.j2
  - postscreen_access.cidr.j2
  - client_access.j2
  - domains.cf.j2

postfix_inet_interfaces: "{{ mail_enabled | bool | ternary('all','loopback-only') }}"
postfix_mydomain: "{{ ((data_center_mode | bool) or (ansible_nodename | regex_findall('\\.') | length) < 2) | ternary(ansible_nodename, None) }}"
# Same recipient delivery delay. With SpamAssassin, set to a number > 0 to prevent monopolization
# of an inundated mailbox since SA has a very limited number of slots to scan mail.
postfix_local_delivery_delay: "{{ ( (spamfilter == 'spamassassin') and (mail_enabled | bool) )  | ternary('3s', '0') }}"
# PostSRS
postsrs_sender_map_port: 10001
postsrs_recipient_map_port: 10002

# Address verification/postscreen map cache
# When data_center_mode is true, replace the maps
# with an aggregate memcache instance
postfix_local_address_verify_map: "proxy:btree:{{ postfix_data_dir }}/verify_cache"
postfix_local_postscreen_cache_map: "proxy:btree:{{ postfix_data_dir }}/postscreen_cache"

postfix_address_verify_map: "{{ (postfix_memcache_server | default('', true) | length > 0) | ternary('memcache:' + postfix_conf_dir + '/memcache-address_verify.cf', postfix_local_address_verify_map) }}"
postfix_postscreen_cache_map: "{{ (postfix_memcache_server | default('', true) | length  > 0) | ternary('memcache:' + postfix_conf_dir + '/memcache-postscreen_cache.cf', postfix_local_postscreen_cache_map) }}"

# Assign 1 server responsibility of periodically purging Postscreen results
postfix_postscreen_cache_cleanup_interval: "{{ (-1 == postfix_postscreen_cache_map.find('memcache:')) | ternary(86400, 0) }}"

# Remove postscreen from proxymap, errors not permitted when in fact in proxy_write_maps
postfix_memcache_maps:
  - config: "memcache-address_verify.cf"
    params:
      - memcache: "{{ (postfix_memcache_server[0] == '/') | ternary('unix', 'inet')}}:{{ postfix_memcache_server }}"
      - backup: "{{ postfix_local_address_verify_map }}"
      - key_format: "vrfy:%s"
  - config: "memcache-postscreen_cache.cf"
    params:
      - memcache: "{{ (postfix_memcache_server[0] == '/') | ternary('unix', 'inet')}}:{{ postfix_memcache_server }}"
      - backup: "{{ postfix_local_postscreen_cache_map }}"
      - key_format: "ps:%s"
