---
# __apnscp_admin_password comes from apnscp/create-admin and only populates if necessary
# Installing as a handler could flush too soon with meta: flush_handlers
- name: Notify admin apnscp is installed
  command: |
    {{ apnscp_root }}/bin/cmd misc_notify_installed {{ __apnscp_admin_password | default("") }}
  when: apnscp_admin_email is defined and apnscp_admin_email != None and __apnscp_admin_password is defined
