---
- name: Fast-forward pending platform migrations
  command: "{{ apnscp_root }}/artisan migrate:platform --ff --force"
  register: r
  changed_when: -1 != r.stdout.find("Fast-forwarded")
  when: __apnscp_admin_password is defined
# __apnscp_admin_password comes from apnscp/create-admin and only populates if necessary
# Installing as a handler could flush too soon with meta: flush_handlers
- name: Notify admin apnscp is installed
  include_tasks: notify.yml
  when: __apnscp_admin_password is defined
