---  
- set_fact:
    password: "{{ lookup('password', '/dev/null chars=ascii_letters length=15') }}"

- debug: msg="{{ password }}"

- name: Enable root PostgreSQL user
  become_user: postgres
  become: True
  postgresql_user: name=root role_attr_flags=SUPERUSER no_password_changes=yes password={{password}} db=template1 encrypted=yes 
  notify: Save PostgreSQL password