# @XXX apnscp/init-fst/tasks/setup-dev include vars/dev.yml 
# clobbers "packages" variable
# no way to limit scope of include_vars to a task yet, i.e. "private: True"
- name: "Template services"
  include_tasks: "template-service.yml"
  with_items: "{{ templated_services }}"
  loop_control:
    label: "Templating {{ item.service }}"
- name: "Install systemd services"
  include_tasks: install-service.yml
  vars: 
    name: "{{ item.name }}"
    files: "{{ item.files }}"
    systemd: "{{ item.systemd | default(None) }}"
  with_items: "{{ services }}"
- file: path={{ hostvars[inventory_hostname][(item.service | replace('-', '_')) + "_service_file"] }} state=absent
  when: "hostvars[inventory_hostname][(item.service | replace('-', '_')) + \"_service_file\"] is defined"
  changed_when: false
  with_items: "{{ templated_services }}"