---
- meta: flush_handlers
- get_argv:
- copy:
    content: |
      #!/bin/sh
      {{ apnscp_bootstrapper_resume_cmd }}
    dest: "{{ apnscp_bootstrapper_resume_script }}"
    mode: 0777
- name: Install Bootstrapper service
  include_role:
    name: apnscp/install-services
  vars:
    templated_services:
      - service: bootstrapper-resume
        template: bootstrapper-resume.j2
    services:
      - name: bootstrapper-resume
        files:
          - src: "{{ bootstrapper_resume_service_file }}"
            dest: /etc/systemd/system/bootstrapper-resume.service
        systemd:
          enabled: yes
- debug: msg="{{ __reboot_template }}"
- pause: seconds=2
- name: Reboot server
  command: systemctl reboot
  when: (reboot | bool)
  # Just in case we make it this far...
- fail:
  when: (reboot | bool)
- name: Fail and save operation
  fail:
    msg: "{{ __failure_template }}"
