---
- include_vars: "{{playbook_dir}}/roles/apnscp/build-php/vars/main.yml"
  when: not apnscp_build_php_vars is defined
- set_fact:
    phpconfig: "{{apnscp_root}}/bin/php-bins/apnscp_php-config"
- include_role:
    name: php/common
    tasks_from: query-extension-dir
- include_role:
    name: php/install-pecl-module
  vars:
    bypass_pecl_ini: 1
    phpize: "{{apnscp_root}}/bin/php-bins/apnscp_phpize"
    pecl_extensions:
      - name: https://github.com/phpredis/phpredis.git
        extension: redis
      - https://github.com/igbinary/igbinary.git
      - https://github.com/krakjoe/apcu.git
    notify: Restart apnscp
- stat:
    path: "{{ php_module_directory }}/ioncube_loader_lin_{{ php_version }}.so"
  register: icst
- include_role:
    name: php/ioncube-loader
  vars:
    php_version: "{{ apnscp_php_version | regex_replace('(\\d\\.\\d)(?:\\.\\d+)?$','\\1') }}{{ php_module_directory | regex_search('-zts$') | ternary('_ts','')}}"
    php_ioncube_loader_module_path: "{{ php_module_directory }}"
    php_ioncube_loader_module_filename: "ioncube_loader_lin_{{ php_version }}.so"
    php_ioncube_loader_config_filename: "00-ioncube.ini"
    php_ioncube_user: "{{ apnscp_system_user }}"
    php_ioncube_group: "{{ apnscp_system_user }}"
    php_extension_conf_paths:
      - "{{ apnscp_root }}/config/php.d"
    handlers:
      - Restart apnscp
  when: not icst.stat.exists
- name: Load opcache into php.ini
  template:
    src: templates/opcache.ini.j2
    dest: "{{ apnscp_root }}/config/php.d/01-opcache.ini"
    force: yes
