---
- stat: path="{{ build_dir }}"
  register: st

- name: Download PHP {{ __php_version }}
  unarchive:
    dest: "{{ work_dir }}"
    src: "http://php.net/get/php-{{ __php_version }}.tar.bz2/from/this/mirror"
    remote_src: yes
  when: not st.stat.exists
- block:   
    - name: Compile PHP {{ __php_version }}      
      shell: "{{ php_configure }} {{ extra_flags }}"
      args:
        chdir: "{{ build_dir }}"       
      environment:
        SCANDIR: "{{ scan_dir }}"
    - make: chdir="{{ build_dir }}" target=all      
    - command: "strip {{ build_dir }}/.libs/libphp{{__php_version | regex_replace('^(\\d+)\\..*$', '\\1') }}.so"
      when: not php_debug
    - make: chdir="{{ build_dir }}" target=install    
    - file: path="{{ scan_dir }}" state=directory
