---
- name: Edit Mail storage location
  lineinfile: 
    path: /etc/login.defs
    regexp: '^[^#]*MAIL_DIR'
    state: present
    line: "MAIL_DIR\t{{maildir_home}}"
- replace:
    path: /etc/Muttrc
    regexp: '^### BEGIN APNSCP(?:[\s\S](?!=^###))+source /etc/Muttrc.local'
  check_mode: yes
  changed_when: not r.changed
  register: r
- lineinfile:
    path: /etc/Muttrc
    regexp: '^[^#]*source\s*/etc/Muttrc\.local'
    state: absent
  when: r.changed
- template:
    src: templates/maildrop-system.j2
    dest: /etc/maildroprc
- file:
    path: "{{ apnscp_filelists }}/siteinfo/etc"
    state: directory
- template: 
    src: templates/maildrop-user.j2
    dest: "{{ apnscp_filelists }}/siteinfo/etc/maildroprc"
- name: Edit Muttrc Mail storage
  blockinfile:
    path: /etc/Muttrc
    marker: "### {mark} APNSCP MANAGED BLOCK ###"
    block: |
      # Local configuration for Mutt.
      set mbox_type=Maildir
      set folder="~/{{maildir_home}}"
      set sort_aux=reverse-date-received
      set sort=threads
      set spoolfile="~/{{maildir_home}}"
      set sort_re
      set header_cache="~/.cache/mutt"
      set tmpdir="{{ mutt_tmp_dir | default('/tmp') }}"
      source /etc/Muttrc.local
- name: Remove root mbox
  file: 
    path: /var/spool/mail/root
    state: absent
- name: Create root spool
  file:
    path: "{{ root_maildir }}"
    state: directory
    mode: 0700
- name: Create maildir sub-folders
  file:
    path: "{{ root_maildir }}/{{item}}"
    state: directory
    mode: 0700
  with_items:
    - new
    - cur
    - old
    - tmp
- name: Enable periodic mail checking for system users
  ini_file:
    path: /etc/profile
    no_extra_spaces: yes
    section: null
    option: MAIL
    value: "{{ maildir_location }}"