---
sysctl_file: /etc/sysctl.d/apnscp.conf
sysctl_config:
  # User services
  net.ipv4.ip_local_reserved_ports: "{{ user_daemons | ternary('40000-49999', '') }}"
  net.ipv4.tcp_slow_start_after_idle: 0
  net.core.somaxconn: 512
  # Fixes ab timeouts
  net.ipv4.tcp_max_syn_backlog: 1024
  net.ipv4.tcp_tw_reuse: 1
  # Restrict dmesg inspection to root
  kernel.dmesg_restrict: 1
  # @TODO Requires further testing
  # Restrict hardlink creation to owner only
  fs.protected_hardlinks: 1
  # Symlink hardening, only follow if outside sticky world-writable directory
  # or when the UID <-> follower match
  fs.protected_symlinks: 1
