---
- name: Update grub
  command: /usr/sbin/grub2-mkconfig -o /etc/grub2.cfg
  # Handle /tmp presence gracefully
- name: Remount tmp
  command: mount -o remount /tmp
  failed_when: false
  tags:
    - skip_ansible_lint
