---
- name: Update grub
  command: /usr/sbin/grub2-mkconfig -o /etc/grub2.cfg
  # Handle /tmp presence gracefully
- name: Remount tmp
  command: mount -o remount /tmp
  failed_when: false
  tags:
    - skip_ansible_lint

- name: Verify quota package installed
  yum: name=quota state=present
  listen: Rebuild quotas
# Make sure new options are picked up
- name: Build quotas
  shell: >
    mount -o remount / && quotaoff -augv && quotacheck -augvm && quotaon -augv
  args:
    warn: false
  listen: Rebuild quotas
