---
- stat: path="{{ apnscp_root }}/storage/opcenter/passwd"
  register: pass
- copy:
    dest: "{{ apnscp_root }}/storage/opcenter/passwd"
    content: "{{ apnscp_admin_user }}:x"
  when: pass.stat.size == 0  
- meta: flush_handlers
- name: Start apnscp
  systemd: state=started name=apnscp enabled=yes
- block:
  - name: "Setting admin password"
    command: "{{ apnscp_root }}/bin/cmd auth_change_password {{ apnscp_admin_password|quote }} {{ apnscp_admin_user|quote }}"
  - debug: msg="Admin password set to {{ apnscp_admin_password }}" verbosity=1
  when: pass.stat.size == 0
- name: "Setting admin email to {{ apnscp_admin_email }}"
  command: "{{ apnscp_root }}/bin/cmd admin_set_email {{ apnscp_admin_email|quote }}"
  when: apnscp_admin_email != None