---
- stat: path="{{ apnscp_root }}/storage/opcenter/passwd"
  register: pass
- copy:
    dest: "{{ apnscp_root }}/storage/opcenter/passwd"
    content: "{{ apnscp_admin_user }}:x"
  when: pass.stat.size == 0  
- meta: flush_handlers
- name: Start apnscp
  systemd: state=started name=apnscp enabled=yes
- set_fact: __apnscp_admin_password={{ apnscp_admin_password }}
  when: pass.stat.size == 0
  # @TODO systemd can be finnicky if apnscpd restarts without formally restarting entire
  # service thus killing it on startup... Add an extra check
- shell: 
    kill -0 "$(cat {{ apnscp_root }}/storage/run/apnscpd.pid)" || ( systemctl restart apnscp && false )
  failed_when: false
  register: o
  until: o.rc == 0 
  retries: 3
  delay: 7
  changed_when: false
- block:
  - name: "Setting admin password"
    command: "{{ apnscp_root }}/bin/cmd auth_change_password {{ __apnscp_admin_password|quote }} {{ apnscp_admin_user|quote }}"
  - debug: msg="Admin password set to {{ __apnscp_admin_password }}" verbosity=1
  when: __apnscp_admin_password is defined
- command: "{{ apnscp_root }}/bin/cmd admin_get_email"
  register: c
  changed_when: false
- name: "Setting admin email to {{ apnscp_admin_email | default('----NOT DEFINED----') }}"
  command: "{{ apnscp_root }}/bin/cmd admin_set_email {{ apnscp_admin_email|quote }}"
  when: not (apnscp_admin_email is none or apnscp_admin_email|regex_search('^\s*$')) and c.stdout != apnscp_admin_email
# @TODO bust out to end? Doesn't make sense in here...
- name: Run initial database migration
  shell: ./artisan migrate --force ; ./artisan config:cache
  args:
    chdir: "{{ apnscp_root}}"
  register: s
  changed_when: '"Nothing to migrate" not in s.stdout'
  when: pass.stat.size == 0