---
- stat: path="{{ apnscp_root }}/storage/opcenter/passwd"
  register: pass
- copy:
    dest: "{{ apnscp_root }}/storage/opcenter/passwd"
    content: "{{ apnscp_admin_user }}:x"
  when: pass.stat.size == 0  
- meta: flush_handlers
- name: Start apnscp
  systemd: state=started name=apnscp enabled=yes
- set_fact: __apnscp_admin_password={{ apnscp_admin_password }}
  when: pass.stat.size == 0
- block:
  - name: "Setting admin password"
    command: "{{ apnscp_root }}/bin/cmd auth_change_password {{ __apnscp_admin_password|quote }} {{ apnscp_admin_user|quote }}"
  - debug: msg="Admin password set to {{ __apnscp_admin_password }}" verbosity=1
  when: __apnscp_admin_password is defined
- name: "Setting admin email to {{ apnscp_admin_email | default('----NOT DEFINED----') }}"
  command: "{{ apnscp_root }}/bin/cmd admin_set_email {{ apnscp_admin_email|quote }}"
  when: apnscp_admin_email != None
# @TODO bust out to end? Doesn't make sense in here...
- name: Run initial database migration
  command: ./artisan migrate --force
  args:
    chdir: "{{ apnscp_root}}"
  register: s
  changed_when: '"Nothing to migrate" not in s.stdout'
  when: pass.stat.size == 0