---
- set_fact:
    PHPMYADMIN_PASSWORD: "{{ phpmyadmin_password }}"
- name: Install phpMyAdmin
  yum: name=phpmyadmin state=present 
  register: installed
- name: Check if phpMyAdmin configured
  stat: path="{{ phpmyadmin_config_file }}"
  register: c
- name: Copy phpMyAdmin configuration template
  template: 
    src: "{{ phpmyadmin_template_file }}"
    dest: "{{ phpmyadmin_config_file }}"
  register: init
  when: not c.stat.exists
- name: Create phpMyAdmin database
  mysql_db:
    name: "{{ phpmyadmin_db }}"
    state: present
  become: yes
  register: import
- name: Import phpMyAdmin database
  mysql_db:
    name: "{{ phpmyadmin_db }}"
    state: import
    target: "{{ phpmyadmin_sql }}"
  become: yes
  when: import.changed

- name: Create phpMyAdmin user
  mysql_user:
    name: "{{ phpmyadmin_user }}"
    password: "{{ PHPMYADMIN_PASSWORD }}"
    host: localhost
    state: present
    priv: "{{ phpmyadmin_db }}.*:ALL"
  become: yes
  when: init is defined and init.changed

- name: Change phpMyAdmin permissions
  file: 
    path: "{{ item }}"
    owner: apache
    group: apache
    recurse: yes
  with_items:
    - "{{ phpmyadmin_storage_path }}"
- name: Remove setup files
  file: 
    path: "{{ phpmyadmin_path }}/{{ item }}"
    state: absent
  with_items:
    - setup
    - sql
