---
rules:
  # Services
  - service: ftp
    state: "{{ ftp_enabled | bool | ternary('enabled', 'disabled') }}"
  # sshd can change ports, covered in system/sshd
  # Mail
  - port: 25/tcp
    state: "{{ mail_enabled | bool | ternary('enabled', 'disabled') }}"
  - port: 465/tcp
    state: "{{ mail_enabled | bool | ternary('enabled', 'disabled') }}"
  - port: 587/tcp
    state: "{{ mail_enabled | bool | ternary('enabled', 'disabled') }}"
  - port: 110/tcp
    state: "{{ mail_enabled | bool | ternary('enabled', 'disabled') }}"
  - port: 143/tcp
    state: "{{ mail_enabled | bool | ternary('enabled', 'disabled') }}"
  - port: 993/tcp
    state: "{{ mail_enabled | bool | ternary('enabled', 'disabled') }}"
  - port: 995/tcp
    state: "{{ mail_enabled | bool | ternary('enabled', 'disabled') }}"
  # HTTP
  - port: 80/tcp
  - port: 443/tcp
  # Panel, non-SSL
  - port: 2082/tcp
    state: "{{ panel_headless | bool | ternary('disabled', 'enabled') }}"
  # Panel
  - port: 2083/tcp
    state: "{{ panel_headless | bool | ternary('disabled', 'enabled') }}"
  # Panel DAV
  - port: 2078/tcp
    state: "{{ panel_headless | bool | ternary('disabled', 'enabled') }}"
  # For service support
  # @TODO integrate port openings in the panel
  - port: "40000-{{ pasv_max_port }}/tcp"
    state: "{{ ftp_enabled | bool | ternary('enabled', 'disabled') }}"
  - port: "{{ (pasv_max_port | int) + 1 }}-49999/tcp"
    state: "{{ user_daemons | bool | ternary('enabled', 'disabled') }}"
  - port: 40000-49999/udp
    state: "{{ user_daemons | bool | ternary('enabled', 'disabled') }}"
  # Database services
  - service: mysql
    state: "{{ allow_remote_db | bool | ternary('enabled', 'disabled') }}"
  - service: postgresql
    state: "{{ allow_remote_db | bool | ternary('enabled', 'disabled') }}"
  # Java
  - port: 8080/tcp
    state: disabled
  - port: 8009/tcp
    state: disabled
  - rule: rule service name="mysql" audit limit value="{{ mysql_conn_limit }}" accept
    zone: public
    state: present
    immediate: false
direct_rules:
  # Block sneaky bastards
  - rule: "-d 127.0.0.1/32 -p tcp -m tcp --dport 25 -j ACCEPT"
    priority: 0
  - rule: "-m owner --uid-owner postfix -j ACCEPT"
    priority: 1
  - rule: "-p tcp -m tcp --dport 25 -m owner --gid-owner postfix -j ACCEPT"
    priority: 1
  - rule: "-p tcp -m tcp --dport 25 -j REJECT --reject-with icmp-port-unreachable"
    priority: 1
  - rule: "-m set --match-set whitelist src -j ACCEPT"
    table: filter
    chain: INPUT
    priority: 0
  - rule: "-m set --match-set blacklist src -j DROP"
    table: filter
    chain: INPUT
    priority: 1
