---
passenger_apache_config: /etc/httpd/conf.d/passenger.conf
passenger_repo: https://github.com/apisnetworks/passenger.git
passenger_repo_ver: local
passenger_home: "{{ apnscp_shared_root}}/passenger"
passenger_log_location: "{{ passenger_home }}/logs"
passenger_fst_log_location: "{{ apnscp_filesystem_template }}/ssh/var/log/httpd/passenger"
# cgroup enforcement will kick in
passenger_max_instances: 5
passenger_max_pool_size: 20
passenger_resolve_symlinks_in_document_root: "Off"
passenger_default_python: 3.4.8
# Automatically update Passenger
passenger_update: true
passenger_sticky_sessions: "Off"