---
- include_role: name="fail2ban/fail2ban-common"
- set_fact:
    whitelist_ip: "{{ lookup('env', 'SSH_CLIENT') | regex_replace(' .+$', '') }}"
  when: not whitelist_ip is defined
- include_tasks: "{{ role_path }}/../fail2ban-common/tasks/whitelist-ip.yml" 
  vars: 
    ip: "{{ whitelist_ip }}"
    mode: "{{ whitelist_mode | default('append') }}"
  when: whitelist_ip != ""