---
- include_vars: "{{ role_path }}/../build-from-source/vars/main.yml"
- include_role:
    name: php/common
    tasks_from: query-extension-dir  
- name: Populate OPCache configuration
  template:
    src: templates/opcache.ini.j2
    dest: "{{ scan_dir }}/01-opcache.ini"
  notify: Restart apache
- stat: path={{ php_main_config }}
  register: s
- name: Set default php.ini
  copy:
    src: files/php.ini
    dest: "{{ php_main_config}}"
  when: not s.stat.exists
- name: Set PHP defaults
  ini_file: 
    section: null
    option: "{{cfgitem.key}}"
    value: "{{cfgitem.value}}"
    dest: "{{ php_main_config }}"
  notify: Restart apache
  with_dict:
    - "pdo_mysql.default_socket": /var/lib/mysql/mysql.sock
    - "mysqli.default_socket": /var/lib/mysql/mysql.sock
    - "mysql.allow_persistent": "Off"
    - "pgsql.allow_persistent": "Off"
    - "upload_max_filesize": "16M"
    - "post_max_size": "20M"
    - "disable_functions": syslog
    - "expose_php": "off"
    - "session.save_path": '"2;/tmp/sessions"'
    - "output_buffering": "4096"
  loop_control:
    loop_var: cfgitem
    label: "Setting {{ cfgitem.key }} in {{ php_main_config }}"