- name: Add {{ _clamav_update_user }} to clamscan group
  user:
    name: "{{ _clamav_update_user }}"
    groups: clamscan
- include_role:
    name: clamav/support
  vars: 
    clamav_scan_cron: "{{ _clamav_scan_cron }}"
    clamav_clamd_config__custom: "{{ _clamav_clamd_config__custom  }}"
    clamav_freshclam_config__custom: "{{ _clamav_freshclam_config__custom }}"
    clamav_clamd_daemon_nicelevel: "{{ _clamav_clamd_daemon_nicelevel}}"
    clamav_clamd_allow_supplementary_groups: "{{ _clamav_allow_supplementary_groups }}"
    clamav_freshclam_database_owner: clamscan
    clamav_user: clamscan
- name: Link /etc/clamd.d/clamd.conf to /etc/clamd.conf
  file: 
    path: /etc/clamd.conf
    state: link
    src: /etc/clamd.d/scan.conf 
- name: "Fix ClamAV ownership"
  file:
    path: /var/lib/clamav
    group: "{{ clamav_group }}"
    recurse: yes
- name: "Reconfigure ClamAV update to use group {{ clamav_group }}"
  ini_file:
    path: /etc/clamav-unofficial-sigs/clamav-unofficial-sigs.conf
    section: null
    option: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
    no_extra_spaces: yes
  with_dict:
    clam_group: "{{ clamav_group }}"