---
- include_vars: dir={{ role_path }}/../support/defaults/
- include_tasks: setup-clamav.yml
  when: clamav_enable
  tags: clamav
- name: Disable ClamAV
  systemd:
    name: "{{ clamav_service }}"
    state: stopped
    enabled: false
  tags: clamav
  register: r
  failed_when: 'r.failed and "Could not find the requested service" not in r.msg'