---
- include_vars: dir={{ role_path }}/../support/defaults/
- include_tasks: setup-clamav.yml
  when: clamav_enabled | bool
  tags: clamav

- name: Disable ClamAV
  systemd:
    name: "{{ clamav_service }}"
    state: stopped
    enabled: false
  tags: clamav
  register: r
  failed_when: 'r.failed and "Could not find the requested service" not in r.msg'
  when: not (clamav_enabled | bool)

- name: "Set clamav installation state in apnscp"
  include_role: name="apnscp/bootstrap" tasks_from="set-config.yml"
  vars:
    section: antivirus
    option: "installed"
    value: "{{ clamav_enabled | bool }}"
