---
- name: Install clamav packages
  yum:
    name: "{{ clamav_packages }}"
    state: present
- name: Validate clamav version
  command: clamav-config --version
  register: v
  changed_when: false
- include_vars: file="{{ role_path }}/../support/defaults/main.yaml" name=local
- set_fact: ignoredVars="{{ ignoredVars + ['AllowSupplementaryGroups'] }}"
  when: v.stdout is version('0.100.0', '>=')
- include_tasks: omit-clamav-var.yml
  vars:
    varname: "{{ item.varname }}"
    ignored: "{{ item.ignored }} "
    dict: "{{ item.dict }}"
  with_items:
    - varname: cleanedVars
      ignored: "{{ ignoredVars }}"
      dict: "{{ local.clamav_clamd_config | combine(_clamav_clamd_config__custom) }}"
    - varname: cleanedFreshclam
      ignored: "{{ ignoredVars }}"
      dict: "{{ local.clamav_freshclam_config | combine(_clamav_freshclam_config__custom) }}"
- include_tasks: configure-clamav.yml
  vars:
    clamav_clamd_config: "{{ cleanedVars }}"
    clamav_freshclam_config: "{{ cleanedFreshclam }}"
- name: Enable ClamAV scanning by apnscp
  user:
    append: true
    groups: "{{ clamav_scan_group }}"
    name: "{{ apnscp_system_user }}"
