---
- name: Install clamav packages
  yum: 
    name: "{{ clamav_packages }}"
    state: present
- name: Validate clamav version
  command: clamav-config --version
  register: v
  changed_when: false
- include_tasks: configure-clamav.yml
  vars:
    clamav_clamd_allow_supplementary_groups: "{{ v.stdout is version('0.100.0', '>=') | ternary('yes', omit) }}"