---  
- set_fact:
    password: "{{ lookup('password', '/dev/null chars=ascii_letters length=15') }}"

- name: Check for password presence
  stat: path={{ passwdfile }}
  register: s

- name: Enable root MySQL user
  mysql_user: name=root priv="*.*:ALL" update_password=always state=present password="{{password}}" encrypted=no 
  notify: Save MySQL password
  when: not s.stat.exists

- name: Remove passwordless users
  shell: >
    echo "DELETE FROM user WHERE password = ''; FLUSH PRIVILEGES;" | mysql mysql