---
- name: Load packages from {{ channel }}
  include_vars:
    file: "vars/rpms/{{ channel }}"
    name: rv
- name: Add RPM channel {{ rv.title | default("")}}
  yum:
    name: "{{ rv.bootstrap.repo_rpm }}"
    state: present
  when:
    - rv.bootstrap is defined
    - rv.bootstrap.repo_rpm is defined
    - rv.when | default(true)
  register: rpm_repo_status

- name: Import RPM key {{ rv.title | default('') }}
  rpm_key:
    key: "{{ rv.bootstrap.repo_key }}"
    state: present
  when:
    - rpm_repo_status.skipped == false
    - rv.bootstrap is defined
    - rv.bootstrap.repo_key is defined

- name: "Install packages"
  yum: state="installed" name="{{ rv.rpms | join(',') }}" skip_broken=yes
  # @XXX Broken in Ansible 2.5.1...
  notify: "{{ rv.notify | default('noop') }}"
  register: c
  when:
    - rv.when | default(true)

  # Workaround for https://github.com/ansible/ansible/issues/26995
- name: "Update packages"
  command: yum update -y --skip-broken {{ rv.rpms|join(' ') }}
  args:
    warn: no
  register: o
  changed_when: -1 == o.stdout.find('No packages marked')
  when: c.changed and rv.state is defined and rv.state == 'latest'
