---
- name: Load packages from {{ channel }}
  include_vars: "vars/rpms/{{ channel }}"

- name: Add RPM channel {{ title | default("")}} 
  yum: 
    name: "{{ bootstrap.repo_rpm }}"
    state: present    
  when:
    - bootstrap is defined
    - bootstrap.repo_rpm is defined
  register: rpm_repo_status

- name: Import RPM key {{ title | default('') }}
  rpm_key:
    key: "{{ bootstrap.repo_key }}"
    state: present
  when:
    - rpm_repo_status.skipped == false
    - bootstrap is defined
    - bootstrap.repo_key is defined
    
- name: "Install packages"  
  yum: state="{{ rpm_state | default('installed') }}" name="{{ pkg }}" skip_broken=yes
  with_items: "{{ rpms }}"
  loop_control:
    loop_var: pkg  
  notify: "{{ notify | default('noop') }}"
