# Install Argos Monit helper
# Must come last since RPM installation triggers a Monit
# restart and unless everything is installed...
---
- name: Install argos
  yum: name=argos state=installed
  register: c
- name: Install ntfy
  pip: name=ntfy state=present version="{{ ntfy_version }}"
- name: Verify monit enabled
  systemd: name=monit state={{ c.changed | ternary('reloaded','started') }} enabled=yes
- name: Update apnscp monitoring profile
  template:
    src: templates/apnscp.conf.j2
    dest: /etc/monit.d/apnscp.conf
    force: yes
  notify: Restart monit
- name: Update monitoring profiles
  include_tasks: toggle-service.yml
  vars:
    name: "{{ item.name }}"
    state: "{{ (item.when | bool) | ternary('enabled', 'disabled') }}"
  with_items:
    - "{{ argos_monitoring_services }}"
- name: Set {{ argos_user }} => {{ argos_delivery_user }} alias
  include_role: name=mail/configure-postfix tasks_from=manage-alias.yml
  vars:
    email: "{{ argos_user }}"
    destination: "{{ argos_delivery_user }}"
