---
- name: Initialize FILESYSTEMTEMPLATE
  file:
    path: "{{apnscp_filesystem_template}}"
    state: directory
  register: fst_created

- ini_file:
    path: "{{apnscp_root}}/config/custom/config.ini"
    section: core
    option: filesystem_template
    value: "{{ apnscp_filesystem_template }}"
- set_fact: __populate_filesystem_template=false
- set_fact: __populate_filesystem_template=true
  when: >
    populate_filesystem_template == "auto" and fst_created.changed or
    populate_filesystem_template == true
- include_tasks: "{{ role_path }}/../../packages/install/tasks/configure-default-vars.yml"
- include_tasks: install-package.yml package="{{ item.package }}"  service="{{item.service}}"
  with_items: "{{ packages }}"
  when: __populate_filesystem_template

- name: "Build synchronizer RPM index"
  command: "{{ synchronizer }} generate"
  when: __populate_filesystem_template

- include_tasks: "{{ role_path }}/tasks/relocate-shared-directory.yml" 
  vars: 
    service: "{{ item.service }}"
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    logrotate_vars: "{{ item.logrotate_vars | default(None) }}"
  with_items: "{{ relocated_paths }}"

- include_tasks: "{{ role_path }}/../bootstrap/tasks/set-platform-version.yml"
  vars:
    version: "{{apnscp_platform_version}}"
- name: "Setup /dev on {{ apnscp_filesystem_template }}"
  include_tasks: setup-dev.yml
- name: "Replace /bin/hostname"
  copy:
    content: |
      #!/bin/sh 
      cat /etc/HOSTNAME
    dest: "{{ apnscp_filesystem_template }}/siteinfo/bin/hostname"
    mode: 0755
# Call after initialization otherwise trigger to create basic directories fails

- name: Create mount point for {{ apnscp_shared_root }} on siteinfo
  file:
    path: "{{ apnscp_filesystem_template }}/siteinfo{{ apnscp_shared_root }}"
    state: directory
    mode: 0711
- file:
    path: "{{ apnscp_filesystem_template }}/siteinfo/home"
    state: directory
    mode: 0755