---
- name: Initialize FILESYSTEMTEMPLATE
  file:
    path: "{{apnscp_filesystem_template}}"
    state: directory
  register: fst_created

- ini_file:
    path: "{{apnscp_root}}/config/custom/config.ini"
    section: core
    option: filesystem_template
    value: "{{ apnscp_filesystem_template }}"

- include_tasks: "{{ role_path }}/../../packages/install/tasks/configure-default-vars.yml"
- include_tasks: install-package.yml package="{{ item.package }}"  service="{{item.service}}"
  with_items: "{{ packages }}"

- name: "Build synchronizer RPM index"
  command: "{{ synchronizer }} generate"

- include_tasks: "{{ role_path }}/tasks/relocate-shared-directory.yml" 
  vars: 
    service: "{{ item.service }}"
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    logrotate_vars: "{{ item.logrotate_vars | default(None) }}"
  with_items: "{{ relocated_paths }}"

- include_tasks: "{{ role_path }}/../bootstrap/tasks/set-platform-version.yml"
  vars:
    version: "{{apnscp_platform_version}}"
- name: "Setup /dev on {{ apnscp_filesystem_template }}"
  include_tasks: setup-dev.yml
