---
- name: "Relocate {{ dest }} to {{ src }} {{ force}}"
  block:
    - file:
        path: "{{ src | dirname }}"
        state: directory
    - stat: path="{{ dest }}"
      register: res
    - file:
        path: "{{ dest }}"
        state: directory
      when: not res.stat.exists and force
    - command: mv "{{ dest }}" "{{ src }}"
      when: (res.stat.exists or force) and (res.stat.islnk is not defined or not res.stat.islnk)
    - file: path="{{ dest }}" src="{{ src }}" state=link force="{{ force | default('no') }}"
- name: "Edit {{ logrotate_vars.file | default('-- SKIPPED --') }}"
  replace:
    path: "{{ logrotate_vars.file }}"
    regexp: '(^|\b){{logrotate_vars.old}}\b'
    replace: '{{ logrotate_vars.new }}'
  when: logrotate_vars | default(None)

- name: Link {{ apnscp_filesystem_template }}/{{ service }}{{ dest }} to {{ src }}
  stat:
    path: "{{ apnscp_filesystem_template }}/{{ service }}{{ dest }}"
  register: r
- block:
  - file:
      path: "{{ apnscp_filesystem_template }}/{{ service }}{{ dest }}"
      state: absent
      follow: no
  - file:
      path: "{{ apnscp_filesystem_template }}/{{ service }}{{ dest | dirname }}"
      state: directory
  - file:
      path: "{{ apnscp_filesystem_template }}/{{ service }}{{ dest }}"
      state: link
      src: "{{ src }}"
    notify:
      - Reload filesystem template
      - "{{ handler | default('noop') }}"
  when: not r.stat.exists or not r.stat.islnk
