- include_vars: ../vars/dev.yml
- include_tasks: setup-dev-per-svc.yml
  with_items: "{{ services }}"
  loop_control:
    loop_var: svcname
- name: "Create pts directory"
  file: 
    path: "{{ base }}/ssh/dev/pts"
    state: directory
- name: "Register rootfs in siteinfo/dev/"
  command: grep -E '/dev\S+\s+/\s+' /proc/mounts
  register: mount
  ignore_errors: yes
  changed_when: false
- block:
    - set_fact:
        dev: '{{ mount.stdout | regex_search("/dev/\S+")}}'
    - command: rsync -a "{{ dev }}" "{{ base }}/siteinfo/{{ dev }}"
      args:
        creates: "{{ base }}/siteinfo/{{ dev }}"
  when: mount.rc == 0
- debug: msg="Failed to detect rootfs, ignoring device creation in {{ apnscp_filesystem_template }}"
  when: mount.rc != 0

