- name: "Create {{ base }}/{{ svcname }}/dev"
  file:
    path: "{{ base }}/{{ svcname }}/dev"
    state: directory
- name: "Link devices for {{ svcname }}"
  synchronize:
    src: "/dev/{{ device }}"
    dest: "{{ base }}/{{ svcname }}/dev/"
    archive: yes
    times: no
  delegate_to: "{{ inventory_hostname }}"
  with_items: "{{ svcdirs[svcname] }}"
  loop_control:
    loop_var: device
