---
- name: noop    
  debug: msg=noop verbosity=4
- name: Restart rsyslog
  systemd: state=restarted name=rsyslog enabled=yes
- name: Restart apnscp
  systemd: state=restarted name=apnscp enabled=yes
- name: Restart apache
  systemd: state=restarted name=httpd enabled=yes
  listen: Restart services
- name: Reload apache
  systemd: state=reloaded name=httpd enabled=yes
- name: Restart dovecot
  systemd: state=restarted name=dovecot enabled=yes
- name: Restart vsftpd
  systemd: state=restarted name=vsftpd  enabled=yes
- name: Restart authlib
  systemd: state=restarted name=courier-authlib enabled=yes
- name: Restart mariadb
  systemd: state=restarted name=mariadb enabled=yes
  listen: Restart mysql
- name: Restart nscd
  systemd: state=restarted name=nscd enabled=yes
- name: Restart postgresql
  systemd: state=restarted name=postgresql 
  listen: Restart services
- name: Reload firewalld
  command: /bin/firewall-cmd --reload
- name: Restart spamassassin
  block:
    - command: rpm -q spamassassin
      ignore_errors: true
      register: sa_present
    - systemd: state=restarted name=spamassassin
      when: sa_present.rc == 0
- name: Restart postfix
  systemd: state=restarted name=postfix enabled=yes
- name: Restart fail2ban
  systemd: state=restarted name=fail2ban enabled=yes
- name: Restart sshd
  systemd: state=restarted name=sshd enabled=yes
- name: Reload filesystem template
  systemd: state=reloaded name=fsmount
- name: Restart virtualhosting
  systemd: state=restarted name=virtualhosting
- name: Rebuild ld cache
  command: chroot {{ apnscp_filesystem_template }}/siteinfo ldconfig
- name: Reload systemd
  systemd: daemon_reload=yes