---
- name: noop    
  debug: msg=noop verbosity=4
- name: Restart rsyslog
  systemd: state=restarted name=rsyslog enabled=yes
- name: Restart apnscp
  systemd: state=restarted name=apnscp enabled=yes
- name: Restart apache
  systemd: state=restarted name=httpd enabled=yes
  listen: Restart services
- name: Restart postgresql
  systemd: state=restarted name=postgresql 
  listen: Restart services
- name: Change apnscp ownership
  command: chown -R {{ apnscp_system_user }}:{{ apnscp_system_user }} {{ apnscp_root }}
- name: Restart spamassassin
  block:
    - command: rpm -q spamassassin
      ignore_errors: true
      register: sa_present
    - systemd: state=restarted name=spamassassin
      when: sa_present.rc == 0
- name: Restart postfix
  systemd: state=restarted name=postfix enabled=yes
- name: Restart fail2ban
  systemd: state=restarted name=fail2ban enabled=yes