---
- debug: msg="{{ DEV_TAG }}"
- set_fact:
    selinux: disabled
    selinuxtype: minimum
  when: not use_selinux
- set_fact:
    selinux: permissive
    selinuxtype: targeted
  when: use_selinux == "debug"
- set_fact:
    selinux: enforcing
    selinuxtype: targeted
  when: use_selinux == true and use_selinux != "debug"
- stat: path=/etc/selinux/config
  register: seconfig
- block:
  - name: Disable SELinux security policy
    ini_file:
      section: null
      path: /etc/selinux/config
      option: SELINUX
      value: "{{ selinux }}"
      no_extra_spaces: yes
    register: c1
  - name: Change SELinux targeting policy
    ini_file:
      section: null
      path: /etc/selinux/config
      option: SELINUXTYPE
      value: "{{ selinuxtype }}"
      no_extra_spaces: yes
    register: c2
  when: seconfig.stat.exists
- name: Save argv
  get_argv:
- include_role: name=common/fail-and-save
  vars:
    reboot: true
    msg: |
      SELINUX POLICY HAS CHANGED. REBOOT SERVER, THEN CONTINUE
      RUNNING PLAYBOOK TO RESUME.
  when: c1.changed or c2.changed and use_selinux != false
