---
- name: "Enabling SSL certificate"
  include_tasks: "{{ role_path }}/../bootstrap/tasks/set-config.yml" 
  vars: 
    section: letsencrypt 
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  with_items:
    - {option: additional_certs, value: "{{ ssl_hostnames | join(',')}}"}
    - {option: debug, value: false}
  when: (ssl_hostnames | list | length) > 0