---
- name: Cast ssl_hostnames to list
  set_fact: ssl_hostnames="['{{ssl_hostnames}}']"
  when: (ssl_hostnames | type_debug) != 'list'
- name: "Enabling SSL certificate"
  include_role: name=apnscp/bootstrap tasks_from="set-config.yml"
  vars:
    section: letsencrypt
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  with_items:
    - {option: additional_certs, value: "{{ ssl_hostnames | join(',')}}"}
    - {option: debug, value: false}
  when: (ssl_hostnames | list | length) > 0
