---
- name: Clone Passenger repository
  git: 
    repo: "{{ passenger_repo }}"
    version: "{{ passenger_repo_ver }}"
    dest: "{{ passenger_home }}"

- name: Set system Ruby for Passenger
  copy:
    dest: "{{ passenger_home }}/.ruby-version"
    content: "{{ sys_ruby_version }}"
- name: Build Passenger
  command: rake apache2
  args:
    chdir: "{{ passenger_home }}"
  notify: Restart apache
- name: Copy Passenger configuration
  template:
    src: templates/passenger.conf.j2
    dest: /etc/httpd/conf.d/passenger.conf
  notify: Restart apache
- name: Create Passenger directories
  file: 
    path: "{{ passenger_home }}/{{ item }}"
    state: directory
  with_items:
    - logs
    - sockets
- file:
    path: "{{ passenger_fst_log_location | dirname}}"
    state: directory
- name: Link passenger log to {{ apnscp_shared_root }}
  file:
    path: "{{ passenger_fst_log_location }}"
    state: link
    src: "{{ passenger_log_location }}"