---
- name: Verify Dovecot starts on boot
  systemd:
    name: dovecot
    enabled: "{{ mail_enabled | bool | ternary('yes', 'no') }}"
    state: "{{ mail_enabled | ternary('started', 'stopped') }}"
  failed_when: false
- name: Copy Dovecot configuration
  template:
    src: "apnscp.conf.j2"
    dest: "{{ dovecot_conf_dir }}/apnscp.conf"
  notify: Restart dovecot

