---
network_setup_firewall_marker: true
# From apnscp-vars.yml
user_daemons: true
panel_headless: false
default_table: filter
default_chain: OUTPUT
default_zone: public
default_immediate: false
default_permanent: true
default_net: ipv4
mysql_conn_limit: 20/s
