---
- include_role: name=fail2ban/fail2ban-common
- name: "Add firewallcmd-ipset-allports action"
  copy: src=files/firewallcmd-ipset-allports.conf dest="{{ fail2ban_directory }}/action.d/"
- name: "Set fail2ban/jail.conf"
  include_role: name=common tasks_from=write-config.yml
  vars:
    file: '{{ fail2ban_directory }}/jail.conf'
    cfgvars: "{{ config_grp.vars }}"
    group: "{{ config_grp.name }}"
    notify: Restart fail2ban
  with_items: "{{ jails }}"
  loop_control:
    loop_var: config_grp
    label: "Configuring jail {{ config_grp.name }}"
- copy:
    src: files/spambots.conf
    dest: "{{ fail2ban_directory }}/filter.d/spambots.conf"
- name: Add preauth disconnect in sshd.conf
  lineinfile:
    line: '         ^%(__prefix_line)sDisconnected from <HOST> port \d+\s+\[preauth\]'
    insertafter: "^.*\\(__prefix_line.*<HOST>.*$\n"
    path: "{{ fail2ban_directory }}/filter.d/sshd.conf"
  notify: Restart fail2ban
- name: Correct failregex in mysqld-auth.conf
  ini_file:
    path: "{{ fail2ban_directory }}/filter.d/mysqld-auth.conf"
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
    state: present
  with_items:
    - section: Definition
      option: failregex
      value: >-
        ^%(__prefix_line)s\s*(?:\d+ |\d{1,2}:\d{2}:\d{2}(?:\s+\d+)?\s*)?\[\w+\] Access denied for user '[^']+'@'<HOST>' (to database '[^']*'|\(using password: (YES|NO)\))*\s*$
    # Bad MariaDB! Bad bad! Pads left two spaces on time
    - section: Init
      option: datepattern
      value: '%%Y(?P<_sep>[-/.])%%m(?P=_sep)%%d\s{1,2}%%H:%%M:%%S(?:,%%f)?'
  notify: Restart fail2ban
- template:
    src: templates/apnscp.conf.j2
    dest: /etc/fail2ban/jail.d/01-apnscp.conf
    force: yes
  notify: Restart fail2ban
- name: Increase max open files for fail2ban-server
  include_role: name=systemd/override-config
  vars:
    service: fail2ban
    config:
      - group: Service
        vars:
          LimitNOFILE: 4096
          TimeoutStartSec: "{{ fail2ban_service_timeout }}"
          TimeoutStopSec: "{{ fail2ban_service_timeout }}"
- include_role: name=apnscp/bootstrap tasks_from=set-config.yml
  vars:
    section: rampart
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  with_items:
    - {option: driver, value: "{{ f2b_rampart_driver }}" }
    - {option: prefix, value: "{{ f2b_rampart_prefix }}" }
- meta: flush_handlers
