---
clamav_enable: false
_clamav_allow_supplementary_groups: yes
_clamav_scan_cron: false
_clamav_clamd_config__custom: 
  LogClean: yes
  ExtendedDetectionInfo: yes
  AllowSupplementaryGroups: "{{ _clamav_allow_supplementary_groups | default(omit) }}"
  ScanPE: yes
  DetectBrokenExecutables: yes
_clamav_clamd_daemon_nicelevel: 5
_clamav_update_user: clamupdate
_clamav_freshclam_config__custom: 
  AllowSupplementaryGroups: yes
clamav_packages:
  - clamav
  - clamav-data
  - clamav-devel
  - clamav-filesystem
  - clamav-lib
  - clamav-scanner
  - clamav-scanner-systemd
  - clamav-server
  - clamav-server-systemd
  - clamav-unofficial-sigs
  - clamav-update