---
- name: Fail if OS is not RHEL/CentOS
  fail:
    msg: OS must be RHEL 7.x/CentOS 7.x - try again!
  when: ansible_os_family != "RedHat"
- name: Fail if RHEL/CentOS is not sufficient version
  fail:
    msg: apnscp requires RHEL 7.4 or greater
  when: ansible_distribution_version is version_compare('7.4.0', '<')
- name: Check virtualization method
  command: systemd-detect-virt -c
  register: o
  changed_when: false
  failed_when: false
- name: Fail if Virtuozzo or OpenVZ used
  fail:
    msg: apnscp cannot run in a container (OpenVZ, Virtuozzo, etc)
  when: o.rc == 0 and not dockerized
- name: Fail if system_hostname is gibberish
  fail:
    msg: >
      system_hostname may not be an IP address and must be of the form server.name.place.
      Leave empty to use the system default.
  when:
    - system_hostname is defined
    - (system_hostname | string) | trim | regex_search('^\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}$')
