---
dovecot_conflicting_conf:
  # Overrides userdb/passdb
  - 10-auth.conf
  # Mailbox namespace inbox=yes
  - 10-mail.conf
dovecot_home: /etc/dovecot
config_file: "{{ dovecot_home }}/apnscp.conf"
postfix_user: postfix
postfix_group: postfix
postfix_auth_socket: /var/spool/postfix/private/auth
dovecot_conf_dir: "{{ dovecot_home }}/conf.d"
# in secure_mode each IMAP connection creates a separate
# process. SSL/TLS also creates a separate process
dovecot_secure_mode: "{{ not has_low_memory | bool }}"