---
- include_tasks: lookup-postfix-db.yml
- name: Forward anacron messages to {{ anacron_address | default("root") }}
  ini_file:
    path: /etc/anacrontab
    section: null
    option: MAILTO
    value: "{{ anacron_address | default('root') }}"
    no_extra_spaces: true
  when: anacron_address is defined
- name: Validate anacron configuration
  command: anacron -T
  changed_when: false
- name: Copy files
  copy: 
    src: "files/{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0755
  with_items: "{{cron_copy}}"
  loop_control:
    label: "Copy {{item.src}} to {{item.dest}}"
- name: Copy templated files
  template: 
    src: "templates/{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0755
  with_items: "{{cron_template}}"
  loop_control:
    label: "Copy {{item.src}} to {{item.dest}}"
- name: Enable apnscp nightly updates
  template:
    src: templates/apnscp_update.sh.j2
    dest: "{{ apnscp_update_cron }}"
    mode: 0755
    force: true
  when: (apnscp_nightly_update | bool) and apnscp_update_policy != false 
- name: Disable apnscp nightly updates
  file: path={{ apnscp_update_cron }} state=absent
  when: not (apnscp_nightly_update | bool) or apnscp_update_policy == false 
- name: Set apnscp update policy
  ini_file: 
    path: /etc/sysconfig/apnscp
    no_extra_spaces: yes
    section: null
    option: APNSCP_UPDATE_POLICY
    value: "{{ (apnscp_update_policy != false) | ternary(apnscp_update_policy, '')}}"