---
- name: Install apnscp build RPMs
  yum: name={{item}} state=installed
  with_items:
    - tokyocabinet-devel
    - httpd-devel  
- include_role:
    name: php/build-from-source  
  notify: "Restart apnscp"
- file:
    src: "{{ apnscp_root }}/bin/php-bins/apnscp_php"
    path: /usr/bin/apnscp_php
    state: link 
