---
- include_vars: file="{{ role_path }}/vars/main.yml"
  when: php_bin is defined
- name: Install apnscp build RPMs
  yum:
    name:
      - tokyocabinet-devel
      - httpd-devel
    state: installed
- name: Verify extension_dir setting
  ini_file:
    path: "{{ apnscp_root }}/config/php.ini"
    section: apnscp
    option: extension_dir
    value: "{{ apnscp_root }}/sys/php/{{ apnscp_php_module_api }}"
- include_role:
    name: php/build-from-source
  vars:
    notify_handler: Restart apnscp
    php_version: "{{ apnscp_php_version }}"
# @XXX php_bin overwritten by including php/build-from-source
- file:
    src: "{{ php_bin }}"
    path: /usr/bin/apnscp_php
    state: link
