---
jails: 
  - name: postfix
    vars:
      port: 25,587,465
      logpath: "%(dovecot_log)s"
      banaction: "{{ f2b_default_banaction }}"    
      enabled: true
      bantime: "{{ f2b_bantime }}"
      findtime: "{{ f2b_findtime }}"
      maxretry: "{{ f2b_maxretry }}"
  - name: evasive
    vars:
      port: 80,443
      logpath: "%(syslog_daemon)s"
      banaction: "{{ f2b_default_banaction }}"
      ignoreip: 127.0.0.1
      filter: "apache-modevasive"
      bantime: "{{ f2b_evasive_bantime | default(120) }}"
      maxretry: "{{ f2b_evasive_maxretry | default (1) }}"
      findtime: "{{ f2b_evasive_findtime | default(3600) }}"
      enabled: true
  - name: recidive
    vars:
      protocol: all
      port: all
      action: iptables-allports
      enabled: true
      # 1 week
      bantime: "{{ f2b_recidive_bantime }}"
      # 1 day
      findtime: "{{ f2b_recidive_findtime }}"
      maxretry: "{{ f2b_recidive_maxretry }}"
  - name: dovecot
    vars:
      port: 110,995,143,993
      bantime: "{{ f2b_bantime }}"
      findtime: "{{ f2b_findtime }}"
      maxretry: "{{ f2b_maxretry }}"
      logpath: "%(dovecot_log)s"
      enabled: true
      banaction: "{{ f2b_default_banaction }}"
  - name: sshd
    vars:
      port: 22
      bantime: "{{ f2b_bantime }}"
      findtime: "{{ f2b_findtime }}"
      maxretry: "{{ sshd_f2b_maxretry | default(f2b_maxretry) | int}}"
      logpath: "%(sshd_log)s"
      enabled: true
  - name: spambots
    vars:
      port: 25,587
      bantime: "{{ f2b_bantime }}"
      findtime: "{{ f2b_findtime }}"
      maxretry: "{{ f2b_maxretry }}"
      logpath: "%(postfix_log)s"
      enabled: true
      banaction: "{{ f2b_default_banaction }}"
  - name: vsftpd
    vars:
      port: ftp,ftp-data,ftps,ftps-data
      bantime: "{{ f2b_bantime }}"
      findtime: "{{ f2b_findtime }}"
      maxretry: "{{ f2b_maxretry }}"
      logpath: "%(vsftpd_log)s"
      enabled: true
      banaction: "{{ f2b_default_banaction }}"