# Conditionally import variables into Playbook
#
# vars:
#   base: base var dictionary to merge into
#   varname: variable to store result
#   prefix: optional variable prefix
#   name: variable override name
#
# See mail/rspamd/tasks/set-rspamd-configuration.yml for example

---
- set_fact:
    "{{ varname }}": >-
      {{ base | combine(lookup('vars', ((prefix | default('', true) | length > 0) | ternary(prefix + '_', '')) +
      ((name | default('', true) | length > 0) | ternary(name + '_', '')) + 'custom_config', default={}), recursive=True) }}
