- name: noop    
  debug: msg="noop handler" verbosity=4
- name: start mariadb
  service: name=mariadb state=started
- name: initialize pgsql
  include_tasks: "{{ role_path }}/handlers/initialize-pgsql.yml"
  listen: install pgsql
- name: enable postgresql
  systemd:
    daemon_reload: yes
    enabled: yes
    state: started
    name: postgresql-{{pgversion}}
  listen: install pgsql