---
- name: Verify if PECL extension installed.
  vars: 
    modname: "{{ extension | basename | regex_replace('\\..+$', '') }}"
  block: 
    - name: "Verify {{ modname }} module installed"
      stat: path="{{ php_module_dir }}/{{ modname }}.so"
      register: stres
    - name: "Build and install {{ modname }} library."
      command: "{{ role_path }}/files/installPecl.sh {{ extension }}"
      environment:
        PHPIZE: "{{ phpize }}"
        PHPCONFIG: "{{ phpconfig }}"
        XTRACFG: "{{ xtracfg }}"    
      when: not stres.stat.exists