# apnscp migration helper
---
- name: Locate migration files
  include_tasks: "{{ playbook_dir }}/migrations/{{ migration_file }}.yml"
  with_items: "{{ (migrations | default([])).split(',') }}"
  register: i
  loop_control:
    label: "Running {{ migration_file }}"
    loop_var: migration_file
  tags: always