---
# fail2ban should catch the majority of offenders...
# sshd begins emitting login failure notices at 1/2 MaxAuthTries 
# raise it for the sake of an admin locking himself out
- name: "Reconfigure sshd"
  blockinfile:
    marker: '# {mark} APNSCP MANAGED BLOCK'
    path: "{{ sshd_config }}"
    content: |
      MaxAuthTries {{ sshd_max_auth_tries }}
      GSSAPIAuthentication no
      X11Forwarding no
    state: present
  notify: Restart sshd