---
- stat: path="{{ horde_path }}"
  register: hs
- include_tasks: install-horde.yml
  when: enable_horde | bool and not hs.stat.exists
- include_tasks: configure-horde.yml
  when: enable_horde | bool
