# Set override configuration with the following,
#
# include_tasks: set-rspamd-configuration
# vars:
#   rspamd_dir: "{{ rspamd_config_dir }}/overrides.d"
#   file: actions.conf
#   config:
#     var1: val1
#     var2: val2
---
- set_fact: cfgpath="{{ rspamd_dir | default(rspamd_config_dir) }}/{{file}}"
- stat: path="{{ cfgpath }}"
  register: st
- name: "{{ st.stat.exists | ternary('Assert permissions on', 'Create file') }} {{ cfgpath}}"
  file:
    path: "{{ cfgpath }}"
    state: "{{ st.stat.exists | ternary('file', 'touch') }}"
    owner: "{{ rspamd_user }}"
    mode: 0600
  register: r
- name: Merge custom config
  block:
    - include_tasks: "{{ playbook_dir }}/roles/common/tasks/implicitly-import-overrides.yml"
      vars:
        base: "{{ config }}"
        varname: __config
        prefix: rspamd
        name: "{{ cfgpath | basename | regex_replace('\\.conf$','') }}"
    - set_fact:
        json: "{{ ('{' + (lookup('file', cfgpath) | default('', True)) + '}') | from_json | combine( __config, recursive=True ) }}"
  rescue:
    - fail: msg="Failed to parse/merge configuration for {{ cfgpath }} - invalid partial JSON?"
- name: "Merging configuration in {{ cfgpath }}"
  copy:
    dest: "{{ cfgpath }}"
    content: '{{ json | to_nice_json | regex_replace("^{|}$", "")}}'
  notify: Restart rspamd
