---
- name: Clone goenv repository
  git: 
    repo: "{{ goenv_repo }}"
    version: "{{ goenv_repo_ver }}"
    dest: "{{ apnscp_filesystem_template }}/{{goenv_service_install}}/{{ git_target }}"
- name: Prepare {{ git_target }}
  file:
    path: "{{ git_target|dirname}}"
    state: directory
- name: Link {{ git_target }}
  file:
    path: "{{ git_target }}"
    src: "{{ apnscp_filesystem_template }}/{{goenv_service_install }}/{{git_target}}"
    state: link
- name: Add {{ git_target }} to wheel
  command: >
    find {{ git_target | quote }} -follow  
      -iname ".git" -prune -o -exec chmod g+w {} + 
      -exec chgrp wheel {} \;
  register: goenv_chmod
  changed_when: goenv_chmod.stdout != ""
- name: Ensure wheel has permissions to install binaries
  file:
    path: "{{ apnscp_filesystem_template }}/{{goenv_service_install }}/{{git_target}}/versions"
    mode: g+rwx
    owner: root
    group: wheel
    state: directory
- name: Get goenv code
  command: "{{ git_target }}/bin/goenv init -"
  environment: 
    GOENV_ROOT: "{{ git_target }}"
  register: goenv_code
- name: Create goenv.sh
  copy:
    dest: "{{ goenv_script }}"
    content: |
      #!/bin/sh
      export GOENV_ROOT="{{ git_target }}"
      {{ goenv_code.stdout }}
    mode: 0644
  register: goenv_create
- name: Link goenv to /usr/bin
  file:
    path: "/usr/bin/goenv"
    src: "{{ git_target }}/bin/goenv"
    state: link
- name: Check for goenv.sh in FST
  stat: path="{{ apnscp_filesystem_template }}/{{ goenv_service_install }}/{{goenv_script}}"
  register: s
- name: Link goenv.sh to FST
  include_tasks: roles/common/tasks/copy-link.yml
  vars: 
    src: "{{ goenv_script }}"
    path: "{{ apnscp_filesystem_template }}/{{ goenv_service_install }}/{{goenv_script}}"
    notify: Reload filesystem template
  when: goenv_create.changed or not s.stat.exists