- debug:
    msg: >
      {{ immediate | default(default_immediate,true) }} | {{ port | default(omit,true) }} |
      {{ service | default(omit,true) }} |
      {{ state | default("enabled",true) }} |
      {{ zone | default(default_zone,true) }} |
      {{ rich | default(omit,true) }} |
      {{ permament | default(default_permanent,true) }}
- name: "Setting rule {{ port | default(rule is defined | ternary(rule, service), true) }} => {{ state | default('enabled',true) }}"
  firewalld:
    immediate: "{{ immediate | default(default_immediate,true) }}"
    port: "{{ port | default(omit,true) }}"
    service: "{{ service | default(omit,true) }}"
    state: '{{ state | default("enabled",true) }}'
    zone: '{{ zone | default(default_zone,true) }}'
    rich_rule: '{{ rich_rule | default(omit,true) }}'
    permanent: '{{ permament | default(default_permanent,true) }}'
  notify: Reload firewalld
