---
- include_role: 
    role: "mail/configure-postfix" 
    tasks_from: "register-password.yml" 
    defaults_from: "main.yml" 
    vars_from: "main.yml"
- name: "Configure {{ daemon_config }}"
  ini_file:
    path: "{{ daemon_config }}"
    section: null
    option: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
    no_extra_spaces: yes
  with_dict: "{{ daemon_vars }}"
  loop_control:
    label: "Edit {{ item.key }}"
  notify: Restart authlib
- name: "Verify permissions on {{ authlib_home }}"
  file: path="{{ authlib_home }}" mode="0710" owner="{{ authlib_user }}" group="{{ authlib_group }}"
- name: "Configure {{ pg_config }}"
  template:
    src: "templates/authpgsqlrc.j2"
    dest: "{{ pg_config }}"
    owner: "{{ authlib_user }}" 
    group: "{{ authlib_group }}"
    mode: 0640
  notify: Restart authlib