---
- include_role: 
    role: "mail/configure-postfix" 
    tasks_from: "register-password.yml" 
    defaults_from: "main.yml" 
    vars_from: "main.yml"
- name: "Configure {{ daemon_config }}"
  ini_file:
    path: "{{ daemon_config }}"
    section: null
    option: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
    no_extra_spaces: yes
  with_dict: "{{ daemon_vars }}"
  loop_control:
    label: "Edit {{ item.key }}"
  notify: Restart authlib
- name: "Verify permissions on {{ authlib_home }}"
  file: path="{{ authlib_home }}" mode="0700" owner="{{ authlib_user }}" group="{{ authlib_group }}"
- name: "Configure {{ pg_config }}"
  lineinfile:
    path: "{{ pg_config }}"
    regexp: '^[#]*{{item.key}}\s+'
    line: "{{item.key}}\t{{item.value}}"
  with_dict: "{{ pg_vars }}"
  notify: Restart authlib