- include_vars: "../defaults/main.yml"
- set_fact:
    ignoreip: "{{ lookup('ini', 'ignoreip section=DEFAULT file={{ fail2ban_jail_config }}') }}"
  when: mode == "append"
- set_fact:
    ignoreip: "127.0.0.1/8"
  when: mode != "append"
- ini_file:
    path: "{{ fail2ban_jail_config }}"
    section: DEFAULT
    option: ignoreip
    value: "{{ ignoreip + ' ' + ip }}"
  notify: Reload fail2ban
  when: mode != "append" or ignoreip and ip not in ignoreip.split(" ")