# @XXX Experimental
---
- name: Toggle caching
  replace:
    path: /etc/nscd.conf
    regexp: '\b(enable-cache\s+{{item.field}}[^\S]+).*$'
    replace: '\1{{item.state}}'
  notify: Restart nscd
  with_items: "{{ nscd_replacements }}"