---
- name: Check browscap.ini presence
  stat: path=/etc/browscap.ini
  register: browscap

- name: Download browscap.ini
  get_url:
    url: http://yum.apnscp.com/browscap.ini
    dest: /etc/browscap.ini
  when: not browscap.stat.exists
