# Create templated files
---
- include_tasks: install.yml
  vars:
    path: "{{ item.path }}"
    service: "{{ item.service }}"
    content: "{{ item.content | default(omit) }}"
    template: "{{ item.template | default(omit) }}"
    force: "{{ item.force | default(false) }}"
  with_items: "{{ files }}"