---
argos_user: monit
argos_delivery_user: root
argos_monitoring_dir: /etc/monit.d
ntfy_version: 2.6.0
argos_monitoring_services:
  - name: spamassassin
    when: "{{ ((spamassassin_enabled | bool) and (mail_enabled | bool)) }}"
  - name: dovecot
    when: "{{ mail_enabled }}"
  - name: vsftpd
    when: "{{ ftp_enabled }}"
