# Initialize custom composer
- name: Check if custom Composer configuration exists
  stat: path={{ apnscp_root }}/config/custom/composer.json
  register: s
- name: Initialize Composer
  command: composer init
  become: yes
  become_user: "{{ apnscp_system_user }}"
  args:
    chdir: "{{ apnscp_root }}/config/custom"
    creates: "{{ apnscp_root}}/config/custom/composer.json"
  when: not s.stat.exists