# Install PostSRS
---
- name: Install postsrsd RPM
  yum: name=postsrsd state=installed
- name: Enable postsrsd
  systemd: name=postsrsd daemon_reload=yes state=started enabled=yes
- name: Set hostname for SRS
  ini_file:
    path: /etc/default/postsrsd
    section: null
    option: SRS_DOMAIN
    value: "{{ srs_domain|default(ansible_fqdn) }}"
  when: (data_center_mode | bool)
  notify: Restart postsrsd