---
services:
  - name: fsmount
    files: 
      - src: fsmount.init
        dest: /etc/systemd/user/fsmount.init
        perm: "0755"
      - src: fsmount.service
        dest: /etc/systemd/system/fsmount.service
    systemd:
      state: started
  - name: populate-tmp
    files: 
      - src: fstmp.init
        dest: /etc/systemd/user/fstmp.init
        perm: "0755"
      - src: populate-tmp.service
        dest: /etc/systemd/system/populate-tmp.service
    systemd:
      state: started
  - name: virtualcroncleanstate
    files: 
      - src: virtualcroncleanstate.service
        dest: /etc/systemd/system/virtualcroncleanstate.service
    systemd:
      state: stopped
  - name: virtualcron
    files: 
      - src: virtualcron.init
        dest: /etc/systemd/user/virtualcron.init
        perm: "0755"
      - src: virtualcron.service
        dest: /etc/systemd/system/virtualcron.service
    systemd:
      state: started
  - name: virtualhosting
    files: 
      - src: virtualhosting.init
        dest: /etc/systemd/user/virtualhosting.init
        perm: "0755"
      - src: virtualhosting.service
        dest: /etc/systemd/system/virtualhosting.service
    systemd:
      state: started
  - name: rc-local
    files: 
      - src: rc-local.service
        dest: /etc/systemd/system/rc-local.service
    systemd:
      enabled: yes
      state: started
